spring.application.name=feign-client
server.port=8082

# URL du service consommateur
consumateur.service.url=http://localhost:8081


# Enable debug logging for web and errors
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.ws=DEBUG
logging.level.com.td1Rest=DEBUG  

# Pretty-print JSON in logs
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Show full stack traces
logging.level.root=INFO